### ISSUE TITLE
Cannot edit workflow

### ISSUE THREAD

**Issue by osamunmun** [higanworks/rundeck-slack-incoming-webhook-plugin#17]
- reproduction procedure
  - 1. enable slack send notification on failure
  - 2. save
  - 3. edit workflow, and save, then got error follows
- Your server environment.
  - use latest(2.6.7) jordan/rundeck container on AWS Elasticbeanstalk
- Software and plugin versions, java environment.
  - Slack plugin(v0.5.dev)
- Other enabled plugins on rundeck.
  - EC2 plugin
- Log: rundeck/service.log

```
object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow
```

error detail

```
Request: /project/xxxxxxx/job/update/8e1c0439-ed70-41f1-b18d-66e18ff8063f?loglevel=INFO&notifyFailureRecipients=&_notifySuccessAttach=&crontab.month._MAY=&crontab=%5Bmonth._MAY%3A%2C+month%3A%5B_MAY%3A%2C+_MAR%3A%2C+_APR%3A%2C+_DEC%3A%2C+_SEP%3A%2C+_FEB%3A%2C+_AUG%3A%2C+_OCT%3A%2C+_JAN%3A%2C+_JUN%3A%2C+_NOV%3A%2C+_JUL%3A%5D%2C+dayOfWeek._SAT%3A%2C+dayOfWeek%3A%5B_SAT%3A%2C+_FRI%3A%2C+_TUE%3A%2C+_SUN%3A%2C+_WED%3A%2C+_THU%3A%2C+_MON%3A%5D%2C+month._MAR%3A%2C+month._APR%3A%2C+dayOfWeek._FRI%3A%2C+month._DEC%3A%2C+dayOfWeek._TUE%3A%2C+dayOfWeek._SUN%3A%2C+month._SEP%3A%2C+month._FEB%3A%2C+month._AUG%3A%2C+month._OCT%3A%2C+dayOfWeek._WED%3A%2C+dayOfWeek._THU%3A%2C+dayOfWeek._MON%3A%2C+month._JAN%3A%2C+month._JUN%3A%2C+month._NOV%3A%2C+month._JUL%3A%5D&_notifyOnstartUrl=&crontab.dayOfWeek._SAT=&crontab.month._MAR=&nodeRankAttribute=&_everyDayOfWeek=&notifyPlugin.onfailure.SlackNotification.config.webhook_url=https%3A%2F%2Fhooks.slack.com%2Fservices%2Fxxxxxxxxx&notifyPlugin=%5Bonfailure.SlackNotification.config.webhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2FTxxxxxxxxx%2C+onfailure%3A%5BSlackNotification.config.webhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2F2FTxxxxxxxxx%2C+SlackNotification%3A%5Bconfig.webhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2F2FTxxxxxxxxx%2C+config%3A%5Bwebhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2FT2FTxxxxxxxxx%5D%5D%2C+type%3ASlackNotification%2C+enabled.SlackNotification%3Atrue%2C+enabled%3A%5BSlackNotification%3Atrue%2C+_SlackNotification%3A%5D%2C+enabled._SlackNotification%3A%5D%2C+onstart.SlackNotification.config.webhook_url%3A%2C+onstart%3A%5BSlackNotification.config.webhook_url%3A%2C+SlackNotification%3A%5Bconfig.webhook_url%3A%2C+config%3A%5Bwebhook_url%3A%5D%5D%2C+type%3ASlackNotification%2C+enabled._SlackNotification%3A%2C+enabled%3A%5B_SlackNotification%3A%5D%5D%2C+onstart.type%3ASlackNotification%2C+onfailure.type%3ASlackNotification%2C+onstart.enabled._SlackNotification%3A%2C+onfailure.enabled.SlackNotification%3Atrue%2C+onfailure.enabled._SlackNotification%3A%2C+onsuccess.SlackNotification.config.webhook_url%3A%2C+onsuccess%3A%5BSlackNotification.config.webhook_url%3A%2C+SlackNotification%3A%5Bconfig.webhook_url%3A%2C+config%3A%5Bwebhook_url%3A%5D%5D%2C+type%3ASlackNotification%2C+enabled._SlackNotification%3A%2C+enabled%3A%5B_SlackNotification%3A%5D%5D%2C+onsuccess.type%3ASlackNotification%2C+onsuccess.enabled._SlackNotification%3A%5D&notifyPlugin.onstart.SlackNotification.config.webhook_url=&notifyStartRecipients=&orchestratorPlugin.subset.config.count=1&orchestratorPlugin=%5Bsubset.config.count%3A1%2C+subset%3A%5Bconfig.count%3A1%2C+config%3A%5Bcount%3A1%5D%5D%2C+maxPercentage.config.percent%3A33%2C+maxPercentage%3A%5Bconfig.percent%3A33%2C+config%3A%5Bpercent%3A33%5D%5D%5D&crontab.month._APR=&dayOfMonth=%3F&_notifyOnfailureEmail=&formInput=true&orig.notifyPlugin.onfailure.SlackNotification.config.webhook_url=https%3A%2F%2Fhooks.slack.com%2Fservices%2Fxxxxxx&orig=%5BnotifyPlugin.onfailure.SlackNotification.config.webhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2FTxxxxx%2C+notifyPlugin%3A%5Bonfailure.SlackNotification.config.webhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2Fxxxxxx%2C+onfailure%3A%5BSlackNotification.config.webhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2Fxxxxxx%2C+SlackNotification%3A%5Bconfig.webhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2xxxxx%2C+config%3A%5Bwebhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2Fxxxxx%5D%5D%5D%2C+onsuccess.SlackNotification.config.webhook_url%3A%2C+onsuccess%3A%5BSlackNotification.config.webhook_url%3A%2C+SlackNotification%3A%5Bconfig.webhook_url%3A%2C+config%3A%5Bwebhook_url%3A%5D%5D%5D%2C+onstart.SlackNotification.config.webhook_url%3A%2C+onstart%3A%5BSlackNotification.config.webhook_url%3A%2C+SlackNotification%3A%5Bconfig.webhook_url%3A%2C+config%3A%5Bwebhook_url%3A%5D%5D%5D%5D%2C+orchestratorPlugin.maxPercentage.config.percent%3A%2C+orchestratorPlugin%3A%5BmaxPercentage.config.percent%3A%2C+maxPercentage%3A%5Bconfig.percent%3A%2C+config%3A%5Bpercent%3A%5D%5D%2C+subset.config.count%3A%2C+subset%3A%5Bconfig.count%3A%2C+config%3A%5Bcount%3A%5D%5D%5D%2C+notifyPlugin.onsuccess.SlackNotification.config.webhook_url%3A%2C+notifyPlugin.onstart.SlackNotification.config.webhook_url%3A%2C+orchestratorPlugin.subset.config.count%3A%5D&_sessionwf=true&doNodedispatch=true&workflow.keepgoing=false&workflow=%5Bkeepgoing%3Afalse%2C+strategy%3Anode-first%5D&crontab.dayOfWeek._FRI=&crontab.month._DEC=&orig.orchestratorPlugin.maxPercentage.config.percent=&crontabString=0+00+00+%3F+*+*+*&crontab.dayOfWeek._TUE=&crontab.dayOfWeek._SUN=&workflow.strategy=node-first&crontab.month._SEP=&SYNCHRONIZER_TOKEN=xxxxxxxx&notifyPlugin.onstart.type=SlackNotification&notifyPlugin.onfailure.type=SlackNotification&crontab.month._FEB=&_sessionopts=true&nodeExcludePrecedence=true&hour=00&SYNCHRONIZER_URI=%2Fproject%2Fxxxxx-api-dev%2Fjob%2Fedit%2F8e1c0439-ed70-41f1-b18d-66e18ff8063f&orchestratorPlugin.maxPercentage.config.percent=33&logOutputThreshold=&_everyMonth=&crontab.month._AUG=&crontab.month._OCT=&nodeThreadcount=1&retry=&scheduleEnabled=true&nodeRankOrderAscending=true&logOutputThresholdStatus=&notifyPlugin.onstart.enabled._SlackNotification=&notifySuccessUrl=&jobName=import+es3&notifyPlugin.onfailure.enabled.SlackNotification=true&description=&_notifyOnfailureUrl=&notified=true&crontab.dayOfWeek._WED=&orig.notifyPlugin.onsuccess.SlackNotification.config.webhook_url=&nodesSelectedByDefault=true&nodeKeepgoing=false&notifyFailureUrl=&everyDayOfWeek=true&scheduled=false&notifyStartSubject=&crontab.dayOfWeek._THU=&orig.notifyPlugin.onstart.SlackNotification.config.webhook_url=&notifyStartUrl=&filter=tags%3Aec2&everyMonth=true&notifySuccessRecipients=&logOutputThresholdAction=halt&notifyPlugin.onfailure.enabled._SlackNotification=&orig.orchestratorPlugin.subset.config.count=&useCrontabString=false&multipleExecutions=false&minute=00&crontab.dayOfWeek._MON=&notifyPlugin.onsuccess.SlackNotification.config.webhook_url=&notifyFailureSubject=&notifyPlugin.onsuccess.type=SlackNotification&_notifyOnstartEmail=&crontab.month._JAN=&groupPath=&_action_Update=Save&_notifyOnsuccessEmail=&orchestratorId=&crontab.month._JUN=&crontab.month._NOV=&_notifyOnsuccessUrl=&notifyPlugin.onsuccess.enabled._SlackNotification=&_notifyFailureAttach=&executionEnabled=true&notifySuccessSubject=&crontab.month._JUL=&timeout=&_sessionEditWFObject=Workflow%3A%28threadcount%3A1%29%7B+%5Bcommand%28+exec%3A+sudo+docker+pull+xxxxx%2Fxxxxx-api+keepgoingOnSuccess%3A+false%29%2C+command%28+exec%3A+docker+run+--rm+-t+xxxxx%2Fxxxxx-api+python+%2Fusr%2Fsrc%2Fapp%2Fexperimental%2Fimport_es3.py+10.81.10.177+keepgoingOnSuccess%3A+false%29%5D+%7D&notifications=%7BeventTrigger%3Donfailure%2C+type%3DSlackNotification%2C+configuration%3D%5Bwebhook_url%3Ahttps%3A%2F%2Fhooks.slack.com%2Fservices%2Fxxxxxxx Message: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow 
Caused by: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow 
Class: ScheduledExecutionController 
At Line: [1733] 
Code Snippet:
```

stack trace

```
org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow
    at rundeck.services.FrameworkService.getFrameworkProject(FrameworkService.groovy:204)
    at rundeck.services.FrameworkService.getFrameworkPropertyResolver(FrameworkService.groovy:307)
    at rundeck.services.NotificationService.validatePluginConfig(NotificationService.groovy:66)
    at rundeck.services.ScheduledExecutionService.validatePluginNotification(ScheduledExecutionService.groovy:1710)
    at rundeck.services.ScheduledExecutionService$__updateNotificationsData_closure47.doCall(ScheduledExecutionService.groovy:1880)
    at rundeck.services.ScheduledExecutionService._updateNotificationsData(ScheduledExecutionService.groovy:1854)
    at rundeck.services.ScheduledExecutionService._doupdate(ScheduledExecutionService.groovy:1623)
    at rundeck.controllers.ScheduledExecutionController$_update_closure51.doCall(ScheduledExecutionController.groovy:1746)
    at rundeck.controllers.ScheduledExecutionController.update(ScheduledExecutionController.groovy:1733)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:349)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by osamunmun** [comment]
After updating `rundeck` to 2.6.8, and `rundeck-slack-incoming-webhook-plugin` from 0.5dev to 0.6dev, I don't get this error.

**Comment by sawanoboly** [comment]
Thank you for report! 

Can I close it ?

**Comment by osamunmun** [comment]
Yes, please close it.
