### ISSUE TITLE
Invalid Payload

### ISSUE THREAD

**Issue by hrzbrg** [higanworks/rundeck-slack-incoming-webhook-plugin#21]
Hi,

today I updated Rundeck and the Slack Plugin to the most recent versions. Unfortunately it started to throw `invalid_payload` errors on me: (censored webhook and urls)

```
ERROR NotificationService: Error sending notification: Notification{eventTrigger='onfailure', type='SlackNotification', content='{"webhook_url":"https://hooks.slack.com/services/..."}'}: class com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Unknown status returned from Slack API: [invalid_payload].
payload=
{
   "attachments":[
      {
         "fallback":"Failed: <https://rundeck.company.it/project/Cronjobs/execution/follow/2729251|Execution #2,729,251> of job <https://rundeck.company.it/project/Cronjobs/job/show/d350ae11-ccca-4ddd-baa3-3b68edd773ff|Logcluster / Move older indices to ondemand nodes>",
         "pretext":"<https://rundeck.company.it/project/Cronjobs/execution/follow/2729251|Execution #2,729,251> of job <https://rundeck.company.it/project/Cronjobs/job/show/d350ae11-ccca-4ddd-baa3-3b68edd773ff|Logcluster / Move older indices to ondemand nodes>",
         "color":"danger",
         "fields":[
            {
               "title":"Job Name",
               "value":"<https://rundeck.company.it/project/Cronjobs/job/show/d350ae11-ccca-4ddd-baa3-3b68edd773ff|Logcluster / Move older indices to ondemand nodes>",
               "short":true
            },
            {
               "title":"Project",
               "value":"Cronjobs",
               "short":true
            },
            {
               "title":"Status",
               "value":"Failed",
               "short":true
            },
            {
               "title":"Execution ID",
               "value":"<https://rundeck.company.it/project/Cronjobs/execution/follow/2729251|#2,729,251>",
               "short":true
            },
            {
               "title":"Options",
               "value":"N/A",
               "short":true
            },
            {
               "title":"Started By",
               "value":"s.herzberg",
               "short":true
            }
            ,{
               "title":"Failed Nodes",
               "value":""rundeck.company.it"",
               "short":false
            }
]
      }
   ]
}

com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Unknown status returned from Slack API: [invalid_payload].
payload=
{
   "attachments":[
      {
         "fallback":"Failed: <https://rundeck.company.it/project/Cronjobs/execution/follow/2729251|Execution #2,729,251> of job <https://rundeck.company.it/project/Cronjobs/job/show/d350ae11-ccca-4ddd-baa3-3b68edd773ff|Logcluster / Move older indices to ondemand nodes>",
         "pretext":"<https://rundeck.company.it/project/Cronjobs/execution/follow/2729251|Execution #2,729,251> of job <https://rundeck.company.it/project/Cronjobs/job/show/d350ae11-ccca-4ddd-baa3-3b68edd773ff|Logcluster / Move older indices to ondemand nodes>",
         "color":"danger",
         "fields":[
            {
               "title":"Job Name",
               "value":"<https://rundeck.company.it/project/Cronjobs/job/show/d350ae11-ccca-4ddd-baa3-3b68edd773ff|Logcluster / Move older indices to ondemand nodes>",
               "short":true
            },
            {
               "title":"Project",
               "value":"Cronjobs",
               "short":true
            },
            {
               "title":"Status",
               "value":"Failed",
               "short":true
            },
            {
               "title":"Execution ID",
               "value":"<https://rundeck.company.it/project/Cronjobs/execution/follow/2729251|#2,729,251>",
               "short":true
            },
            {
               "title":"Options",
               "value":"N/A",
               "short":true
            },
            {
               "title":"Started By",
               "value":"s.herzberg",
               "short":true
            }
            ,{
               "title":"Failed Nodes",
               "value":""rundeck.company.it"",
               "short":false
            }
]
      }
   ]
}

        at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.postNotification(SlackNotificationPlugin.java:125)
        at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:475)
        at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:337)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:146)
        at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:88)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:85)
        at rundeck.services.ExecutionService$_saveExecutionState_closure60.doCall(ExecutionService.groovy:2089)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:1994)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:480)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:418)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:490)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:146)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:74)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:73)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by sawanoboly** [comment]
> ```
>            "value":""rundeck.company.it"",
> ```

hmm... It seems invalid JSON due to this line .

**Comment by hrzbrg** [comment]
Oh, I totally overlooked that. Was able to spot the mistake in the Rundeck config after that: `<node name="&quot;rundeck.company.it&quot;"....` was in the resources.xml which was caused by quotes in `framework.server.name` in the `/etc/rundeck/framework.properties`
