### ISSUE TITLE
Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by mathieuchateau** [higanworks/rundeck-slack-incoming-webhook-plugin#24]
Hello,

plugin is not working on our rundeck, version 2.6.9-1.

Here is the error:

> 2016-09-27 23:40:09,691 [quartzScheduler_Worker-27] ERROR grails.app.services.rundeck.services.NotificationService - Error sending notification: Notification{eventTrigger='onsuccess', type='SlackNotification', content='{"webhook_url":"https://hooks.slack.com/services/Obfuscatedstring"}'}: class com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Error putting data to Slack URL: [java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty].
> com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Error putting data to Slack URL: [java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty].
>         at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.putRequestStream(SlackNotificationPlugin.java:221)
>         at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.invokeSlackAPIMethod(SlackNotificationPlugin.java:180)
>         at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.postNotification(SlackNotificationPlugin.java:117)
>         at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:489)
>         at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:351)
>         at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:146)
>         at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:88)
>         at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:85)
>         at rundeck.services.ExecutionService$_saveExecutionState_closure59.doCall(ExecutionService.groovy:2157)
>         at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2062)
>         at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:486)
>         at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:424)
>         at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:496)
>         at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:146)
>         at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:74)
>         at com.codahale.metrics.Timer.time(Timer.java:99)
>         at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:73)
>         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
>         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
> Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>         at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.putRequestStream(SlackNotificationPlugin.java:216)
>         ... 18 more
> Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>         ... 19 more
> Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>         at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
>         at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
>         at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
>         ... 19 more
> '''

Thanks for ypur help

**Comment by charlescoupeau** [comment]
Hello,

Have you found the solution because we encounter problem with this plugin. Version 2.7.3.

> ERROR grails.app.services.rundeck.services.NotificationService - Error sending notification: Notification{eventTrigger='onfailure', type='SlackNotification', content='{"webhook_url":"https://rocket.univ-rennes1.fr/hooks/......."}'}: class com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Error putting data to Slack URL: [sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target].
com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Error putting data to Slack URL: [sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target].
	at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.putRequestStream(SlackNotificationPlugin.java:221)
	at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.invokeSlackAPIMethod(SlackNotificationPlugin.java:180)
	at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.postNotification(SlackNotificationPlugin.java:117)
	at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:490)
	at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:352)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:147)
	at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:89)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:86)
	at rundeck.services.ExecutionService$_saveExecutionState_closure61.doCall(ExecutionService.groovy:2320)
	at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2221)
	at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:511)
	at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:449)
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:521)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:164)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:91)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:90)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.putRequestStream(SlackNotificationPlugin.java:216)
	... 18 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	... 19 more

> 

Thanks.

**Comment by jtexier** [comment]
Hello,

I had the same problem with Rundeck 2.9.3-1.
You should take a look to the trustore used by java when launching rundeckd service. 

Check the options used on /etc/rundeck/profile. 
It works for me when I set the default java cacert 
on javax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts
