### ISSUE TITLE
Plugin does not work with docker container

### ISSUE THREAD

**Issue by d3vkit** [higanworks/rundeck-slack-incoming-webhook-plugin#45]
I am using the [official docker image for rundeck](https://hub.docker.com/r/rundeck/rundeck), which does not create the same directory structure as the plugin expects. I have a workaround right now, but the hard-coded directory path throws.

[This line](https://github.com/higanworks/rundeck-slack-incoming-webhook-plugin/blob/d4b5a28cbb942909051c34cd1098e2ee0b89ee1a/src/main/java/com/bitplaces/rundeck/plugins/slack/SlackNotificationPlugin.java#L122
) throws when attempting to send a notification because the directory doesn't exist:

```java
final TemplateLoader[] loaders = {
    new FileTemplateLoader(new File("/etc/rundeck")), // Throws because dir doesn't exist
    new ClassTemplateLoader(SlackNotificationPlugin.class, "/templates")
};
```
The [log can be viewed here](https://gist.github.com/d3vkit/c90911b54562f5911b91a8205794b72b) if you would like; it is mostly:

```bash
2019-02-18 06:25:01.857 ERROR --- [eduler_Worker-3] c.b.r.p.slack.SlackNotificationPlugin    : Got an exception from Freemarker: /etc/rundeck does not exist.

java.io.FileNotFoundException: /etc/rundeck does not exist.
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:124)
	at java.security.AccessController.doPrivileged(Native Method)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:121)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:107)
	at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.<init>(SlackNotificationPlugin.java:121)
	at sun.reflect.GeneratedConstructorAccessor215.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```
----

Workaround:

There is an `/etc` folder in `/home/rundeck` on the image, so in my Dockerfile where I am loading the plugin I created `/home/rundeck/etc/rundeck` and symlinked it to `/etc/rundeck`, and this solved the issue.

```Dockerfile
USER root
...
RUN mkdir /home/rundeck/etc/rundeck \
      && chown rundeck:rundeck /home/rundeck/etc/rundeck \
      && ln -s /home/rundeck/etc/rundeck /etc/rundeck
```

edit: it occurs to me that I can probably just make the actual directory, but at any rate, the directory doesn't exist in the docker image.

If you would like I can submit a PR to add this info the README. Otherwise it will probably take me a reallllly long time to figure out a PR to fix the issue.

Thanks for the work on this, it's a really useful plugin!

**Comment by nikukyugamer** [comment]
@d3vkit 
Wow! It's a great solution!
Thanks!
