### ISSUE TITLE
No payload received

### ISSUE THREAD

**Issue by eiroh** [higanworks/rundeck-slack-incoming-webhook-plugin#6]
com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Unknown status returned from Slack API: [No payload received].
payload=%7B%0A+++%22attachments%22%3A%5B%0A++++++%7B%0A+++++++++%22fallback%22%3A%22Succeeded%3A+%3Chttp%3A%2F%2Fxxx.xxx.xxx.xxx%2Frundeck%2Fproject%2Fxxx%2Fexecution%2Ffollow%2F133%7CExecution+%23133%3E+of+job+%3Chttp%3A%2F%2Fxxx.xxx.xxx%2Frundeck%2Fproject%2Fxxx%2Fjob%2Fshow%2F2dbd2d5a-b5ab-4ebf-a893-88a5717187f3%7Ctest%3E%22%2C%0A+++++++++%22pretext%22%3A%22%3Chttp%3A%2F%2Fxxx.xxx.xxx.xxx%2Frundeck%2Fproject%2Fxxx%2Fexecution%2Ffollow%2F133%7CExecution+%23133%3E+of+job+%3Chttp%3A%2F%2Fxxx.xxx.xxx.xxx%2Frundeck%2Fproject%2Fxxx%2Fjob%2Fshow%2F2dbd2d5a-b5ab-4ebf-a893-88a5717187f3%7Ctest%3E%22%2C%0A+++++++++%22color%22%3A%22good%22%2C%0A+++++++++%22fields%22%3A%5B%0A++++++++++++%7B%0A+++++++++++++++%22title%22%3A%22Job+Name%22%2C%0A+++++++++++++++%22value%22%3A%22%3Chttp%3A%2F%2Fxxx.xxx.xxx.xxx%2Frundeck%2Fproject%2Ftest%2Fjob%2Fshow%2F2dbd2d5a-b5ab-4ebf-a893-88a5717187f3%7Ctest%3E%22%2C%0A+++++++++++++++%22short%22%3Atrue%0A++++++++++++%7D%2C%0A++++++++++++%7B%0A+++++++++++++++%22title%22%3A%22Project%22%2C%0A+++++++++++++++%22value%22%3A%22test%22%2C%0A+++++++++++++++%22short%22%3Atrue%0A++++++++++++%7D%2C%0A++++++++++++%7B%0A+++++++++++++++%22title%22%3A%22Status%22%2C%0A+++++++++++++++%22value%22%3A%22Succeeded%22%2C%0A+++++++++++++++%22short%22%3Atrue%0A++++++++++++%7D%2C%0A++++++++++++%7B%0A+++++++++++++++%22title%22%3A%22Execution+ID%22%2C%0A+++++++++++++++%22value%22%3A%22%3Chttp%3A%2F%2Fxxx.xxx.xxx.xxx%2Frundeck%2Fproject%2Fxxx%2Fexecution%2Ffollow%2F133%7C%23133%3E%22%2C%0A+++++++++++++++%22short%22%3Atrue%0A++++++++++++%7D%0A%5D%0A++++++%7D%0A+++%5D%0A%7D%0A%0A
        at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.postNotification(SlackNotificationPlugin.java:130)
        at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:471)
        at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:333)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:142)
        at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:84)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:81)
        at rundeck.services.ExecutionService$_saveExecutionState_closure54.doCall(ExecutionService.groovy:1904)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:1809)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure3.doCall(ExecutionJob.groovy:449)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:392)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:458)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:143)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by sawanoboly** [comment]
hmm.. It looks like valid JSON. Is notification always fail ?

```
{
   "attachments" : [
      {
         "pretext" : "<http://xxx.xxx.xxx.xxx/rundeck/project/xxx/execution/follow/133|Execution+#133>+of+job+<http://xxx.xxx.xxx.xxx/rundeck/project/xxx/job/show/2dbd2d5a-b5ab-4ebf-a893-88a5717187f3|test>",
         "color" : "good",
         "fields" : [
            {
               "title" : "Job+Name",
               "value" : "<http://xxx.xxx.xxx.xxx/rundeck/project/test/job/show/2dbd2d5a-b5ab-4ebf-a893-88a5717187f3|test>",
               "short" : true
            },
            {
               "short" : true,
               "value" : "test",
               "title" : "Project"
            },
            {
               "title" : "Status",
               "value" : "Succeeded",
               "short" : true
            },
            {
               "title" : "Execution+ID",
               "value" : "<http://xxx.xxx.xxx.xxx/rundeck/project/xxx/execution/follow/133|#133>",
               "short" : true
            }
         ],
         "fallback" : "Succeeded:+<http://xxx.xxx.xxx.xxx/rundeck/project/xxx/execution/follow/133|Execution+#133>+of+job+<http://xxx.xxx.xxx/rundeck/project/xxx/job/show/2dbd2d5a-b5ab-4ebf-a893-88a5717187f3|test>"
      }
   ]
}
```

**Comment by eiroh** [comment]
Yes, always fail on Success, Failure, Start.

2015-07-22 14:28:27,952 [quartzScheduler_Worker-9] ERROR grails.app.services.rundeck.services.NotificationService - Error sending notification: Notification{eventTrigger='onsuccess', type='SlackNotification', content='{"webhook_url":"https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxxxxxx"}'}: class com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Unknown status returned from Slack API: [No payload received].

CentOS Linux release 7.1.1503 (Core) / rundeck-2.5.2-1.8.GA.noarch
